# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI/PRE_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.tabWidget.setFont(font)
        self.tabWidget.setStatusTip("")
        self.tabWidget.setObjectName("tabWidget")
        self.deal_tab = QtWidgets.QWidget()
        self.deal_tab.setObjectName("deal_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.deal_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plot_widget = QtWidgets.QWidget(self.deal_tab)
        self.plot_widget.setObjectName("plot_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.plot_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.DIS_canvas = QtWidgets.QWidget(self.plot_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DIS_canvas.sizePolicy().hasHeightForWidth())
        self.DIS_canvas.setSizePolicy(sizePolicy)
        self.DIS_canvas.setMinimumSize(QtCore.QSize(840, 320))
        self.DIS_canvas.setObjectName("DIS_canvas")
        self.Dis_Layout = QtWidgets.QVBoxLayout(self.DIS_canvas)
        self.Dis_Layout.setObjectName("Dis_Layout")
        self.horizontalLayout.addWidget(self.DIS_canvas)
        self.verticalLayout_2.addWidget(self.plot_widget)
        self.input_widget = QtWidgets.QWidget(self.deal_tab)
        self.input_widget.setObjectName("input_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.input_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.input_widget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.shiyu_btn = QtWidgets.QRadioButton(self.input_widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.shiyu_btn.setFont(font)
        self.shiyu_btn.setChecked(True)
        self.shiyu_btn.setObjectName("shiyu_btn")
        self.gridLayout.addWidget(self.shiyu_btn, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.input_widget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.input_widget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.val_pre_edit = QtWidgets.QLineEdit(self.input_widget)
        self.val_pre_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.val_pre_edit.setObjectName("val_pre_edit")
        self.gridLayout.addWidget(self.val_pre_edit, 2, 1, 1, 2)
        self.overlap_edit = QtWidgets.QLineEdit(self.input_widget)
        self.overlap_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.overlap_edit.setObjectName("overlap_edit")
        self.gridLayout.addWidget(self.overlap_edit, 1, 1, 1, 2)
        self.data_long_edit = QtWidgets.QLineEdit(self.input_widget)
        self.data_long_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.data_long_edit.setObjectName("data_long_edit")
        self.gridLayout.addWidget(self.data_long_edit, 0, 1, 1, 2)
        self.unlabel_edit = QtWidgets.QLineEdit(self.input_widget)
        self.unlabel_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.unlabel_edit.setObjectName("unlabel_edit")
        self.gridLayout.addWidget(self.unlabel_edit, 3, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.input_widget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.deal_btn = QtWidgets.QPushButton(self.input_widget)
        self.deal_btn.setObjectName("deal_btn")
        self.gridLayout.addWidget(self.deal_btn, 6, 2, 1, 1)
        self.piny_btn = QtWidgets.QRadioButton(self.input_widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.piny_btn.setFont(font)
        self.piny_btn.setObjectName("piny_btn")
        self.gridLayout.addWidget(self.piny_btn, 4, 1, 1, 1)
        self.select_floder_btn = QtWidgets.QPushButton(self.input_widget)
        self.select_floder_btn.setObjectName("select_floder_btn")
        self.gridLayout.addWidget(self.select_floder_btn, 6, 0, 1, 2)
        self.plot_check = QtWidgets.QCheckBox(self.input_widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.plot_check.setFont(font)
        self.plot_check.setChecked(True)
        self.plot_check.setObjectName("plot_check")
        self.gridLayout.addWidget(self.plot_check, 4, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.input_widget)
        self.tabWidget.addTab(self.deal_tab, "")
        self.analy_tab = QtWidgets.QWidget()
        self.analy_tab.setObjectName("analy_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.analy_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.load_btn = QtWidgets.QPushButton(self.analy_tab)
        self.load_btn.setObjectName("load_btn")
        self.gridLayout_2.addWidget(self.load_btn, 2, 0, 1, 1)
        self.draw_btn = QtWidgets.QPushButton(self.analy_tab)
        self.draw_btn.setObjectName("draw_btn")
        self.gridLayout_2.addWidget(self.draw_btn, 2, 1, 1, 1)
        self.SP_canvas = QtWidgets.QWidget(self.analy_tab)
        self.SP_canvas.setObjectName("SP_canvas")
        self.SP_Layout = QtWidgets.QVBoxLayout(self.SP_canvas)
        self.SP_Layout.setObjectName("SP_Layout")
        self.gridLayout_2.addWidget(self.SP_canvas, 1, 0, 1, 2)
        self.data_name_label = QtWidgets.QLabel(self.analy_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_name_label.sizePolicy().hasHeightForWidth())
        self.data_name_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.data_name_label.setFont(font)
        self.data_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.data_name_label.setObjectName("data_name_label")
        self.gridLayout_2.addWidget(self.data_name_label, 0, 0, 1, 2)
        self.tabWidget.addTab(self.analy_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.data_long_edit, self.overlap_edit)
        MainWindow.setTabOrder(self.overlap_edit, self.val_pre_edit)
        MainWindow.setTabOrder(self.val_pre_edit, self.unlabel_edit)
        MainWindow.setTabOrder(self.unlabel_edit, self.shiyu_btn)
        MainWindow.setTabOrder(self.shiyu_btn, self.piny_btn)
        MainWindow.setTabOrder(self.piny_btn, self.plot_check)
        MainWindow.setTabOrder(self.plot_check, self.select_floder_btn)
        MainWindow.setTabOrder(self.select_floder_btn, self.deal_btn)
        MainWindow.setTabOrder(self.deal_btn, self.load_btn)
        MainWindow.setTabOrder(self.load_btn, self.draw_btn)
        MainWindow.setTabOrder(self.draw_btn, self.tabWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "前处理"))
        self.label_4.setStatusTip(_translate("MainWindow", "半监督时， 无标签样本所占比例"))
        self.label_4.setText(_translate("MainWindow", "无标签比例："))
        self.shiyu_btn.setStatusTip(_translate("MainWindow", "输入为时域信号"))
        self.shiyu_btn.setText(_translate("MainWindow", "时域信号"))
        self.label_3.setStatusTip(_translate("MainWindow", "训练时验证集比例"))
        self.label_3.setText(_translate("MainWindow", "验证集比例："))
        self.label.setStatusTip(_translate("MainWindow", "每段样本的长度"))
        self.label.setText(_translate("MainWindow", "样本长度："))
        self.val_pre_edit.setStatusTip(_translate("MainWindow", "0 - 100"))
        self.overlap_edit.setStatusTip(_translate("MainWindow", "0 - 100"))
        self.data_long_edit.setStatusTip(_translate("MainWindow", "data length"))
        self.unlabel_edit.setStatusTip(_translate("MainWindow", "0 - 100"))
        self.label_2.setStatusTip(_translate("MainWindow", "切分样本时重叠比例"))
        self.label_2.setText(_translate("MainWindow", "重叠率："))
        self.deal_btn.setStatusTip(_translate("MainWindow", "进行数据预处理"))
        self.deal_btn.setText(_translate("MainWindow", "预处理"))
        self.piny_btn.setStatusTip(_translate("MainWindow", "输入为频域信号"))
        self.piny_btn.setText(_translate("MainWindow", "频域信号"))
        self.select_floder_btn.setStatusTip(_translate("MainWindow", "选择数据所在文件夹， 其子文件夹包括类别，再下一级包括数据样本"))
        self.select_floder_btn.setText(_translate("MainWindow", "选择文件夹"))
        self.plot_check.setStatusTip(_translate("MainWindow", "是否绘制数据分布图"))
        self.plot_check.setText(_translate("MainWindow", "绘制分布图"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.deal_tab), _translate("MainWindow", "数据处理"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.deal_tab), _translate("MainWindow", "支持用户自行定义截取信号长度、输入信号类型（如时域信号、频域信号等）"))
        self.load_btn.setStatusTip(_translate("MainWindow", "加载单个样本， 进行时频分析"))
        self.load_btn.setText(_translate("MainWindow", "加载样本"))
        self.draw_btn.setStatusTip(_translate("MainWindow", "时域、频域分析"))
        self.draw_btn.setText(_translate("MainWindow", "绘图"))
        self.data_name_label.setText(_translate("MainWindow", "Name"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.analy_tab), _translate("MainWindow", "时频分析"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.analy_tab), _translate("MainWindow", "可以显示信号的时域、频域等特征"))

