# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI/SUFF_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.semi_sup_widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.semi_sup_widget.sizePolicy().hasHeightForWidth())
        self.semi_sup_widget.setSizePolicy(sizePolicy)
        self.semi_sup_widget.setMinimumSize(QtCore.QSize(500, 250))
        self.semi_sup_widget.setMaximumSize(QtCore.QSize(10000, 10000))
        self.semi_sup_widget.setObjectName("semi_sup_widget")
        self.semi_sup_Layout = QtWidgets.QVBoxLayout(self.semi_sup_widget)
        self.semi_sup_Layout.setObjectName("semi_sup_Layout")
        self.gridLayout.addWidget(self.semi_sup_widget, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.choice_unsup = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choice_unsup.sizePolicy().hasHeightForWidth())
        self.choice_unsup.setSizePolicy(sizePolicy)
        self.choice_unsup.setMinimumSize(QtCore.QSize(80, 50))
        self.choice_unsup.setObjectName("choice_unsup")
        self.verticalLayout_7.addWidget(self.choice_unsup)
        self.unsup_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.unsup_btn.setMinimumSize(QtCore.QSize(80, 50))
        self.unsup_btn.setObjectName("unsup_btn")
        self.verticalLayout_7.addWidget(self.unsup_btn)
        self.unsup_tb = QtWidgets.QPushButton(self.groupBox_3)
        self.unsup_tb.setMinimumSize(QtCore.QSize(80, 50))
        self.unsup_tb.setObjectName("unsup_tb")
        self.verticalLayout_7.addWidget(self.unsup_tb)
        self.unsup_tb_close = QtWidgets.QPushButton(self.groupBox_3)
        self.unsup_tb_close.setEnabled(False)
        self.unsup_tb_close.setMinimumSize(QtCore.QSize(80, 50))
        self.unsup_tb_close.setObjectName("unsup_tb_close")
        self.verticalLayout_7.addWidget(self.unsup_tb_close)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.gridLayout.addWidget(self.widget, 2, 1, 1, 1)
        self.unsup_widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unsup_widget.sizePolicy().hasHeightForWidth())
        self.unsup_widget.setSizePolicy(sizePolicy)
        self.unsup_widget.setMinimumSize(QtCore.QSize(500, 250))
        self.unsup_widget.setMaximumSize(QtCore.QSize(10000, 10000))
        self.unsup_widget.setObjectName("unsup_widget")
        self.unsup_Layout = QtWidgets.QVBoxLayout(self.unsup_widget)
        self.unsup_Layout.setObjectName("unsup_Layout")
        self.gridLayout.addWidget(self.unsup_widget, 2, 0, 1, 1)
        self.sup_widght = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sup_widght.sizePolicy().hasHeightForWidth())
        self.sup_widght.setSizePolicy(sizePolicy)
        self.sup_widght.setMinimumSize(QtCore.QSize(500, 250))
        self.sup_widght.setMaximumSize(QtCore.QSize(100000, 100000))
        self.sup_widght.setObjectName("sup_widght")
        self.sup_Layout = QtWidgets.QVBoxLayout(self.sup_widght)
        self.sup_Layout.setObjectName("sup_Layout")
        self.gridLayout.addWidget(self.sup_widght, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.choice_semi_sup = QtWidgets.QPushButton(self.groupBox_2)
        self.choice_semi_sup.setMinimumSize(QtCore.QSize(80, 50))
        self.choice_semi_sup.setObjectName("choice_semi_sup")
        self.verticalLayout_6.addWidget(self.choice_semi_sup)
        self.semi_sup_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.semi_sup_btn.setMinimumSize(QtCore.QSize(80, 50))
        self.semi_sup_btn.setObjectName("semi_sup_btn")
        self.verticalLayout_6.addWidget(self.semi_sup_btn)
        self.semisup_tb = QtWidgets.QPushButton(self.groupBox_2)
        self.semisup_tb.setMinimumSize(QtCore.QSize(80, 50))
        self.semisup_tb.setObjectName("semisup_tb")
        self.verticalLayout_6.addWidget(self.semisup_tb)
        self.semisup_tb_close = QtWidgets.QPushButton(self.groupBox_2)
        self.semisup_tb_close.setEnabled(False)
        self.semisup_tb_close.setMinimumSize(QtCore.QSize(80, 50))
        self.semisup_tb_close.setObjectName("semisup_tb_close")
        self.verticalLayout_6.addWidget(self.semisup_tb_close)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.gridLayout.addWidget(self.widget_2, 1, 1, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.choice_sup = QtWidgets.QPushButton(self.groupBox)
        self.choice_sup.setMinimumSize(QtCore.QSize(80, 50))
        self.choice_sup.setObjectName("choice_sup")
        self.verticalLayout_5.addWidget(self.choice_sup)
        self.sup_btn = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sup_btn.sizePolicy().hasHeightForWidth())
        self.sup_btn.setSizePolicy(sizePolicy)
        self.sup_btn.setMinimumSize(QtCore.QSize(80, 50))
        self.sup_btn.setObjectName("sup_btn")
        self.verticalLayout_5.addWidget(self.sup_btn)
        self.sup_tb = QtWidgets.QPushButton(self.groupBox)
        self.sup_tb.setMinimumSize(QtCore.QSize(80, 50))
        self.sup_tb.setObjectName("sup_tb")
        self.verticalLayout_5.addWidget(self.sup_tb)
        self.sup_tb_close = QtWidgets.QPushButton(self.groupBox)
        self.sup_tb_close.setEnabled(False)
        self.sup_tb_close.setMinimumSize(QtCore.QSize(80, 50))
        self.sup_tb_close.setObjectName("sup_tb_close")
        self.verticalLayout_5.addWidget(self.sup_tb_close)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.gridLayout.addWidget(self.widget_3, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "后处理"))
        self.groupBox_3.setTitle(_translate("MainWindow", "无监督学习"))
        self.choice_unsup.setText(_translate("MainWindow", "选择exp"))
        self.unsup_btn.setText(_translate("MainWindow", "快速查看"))
        self.unsup_tb.setText(_translate("MainWindow", "TB查看"))
        self.unsup_tb_close.setText(_translate("MainWindow", "关闭端口"))
        self.groupBox_2.setTitle(_translate("MainWindow", "半监督学习"))
        self.choice_semi_sup.setText(_translate("MainWindow", "选择exp"))
        self.semi_sup_btn.setText(_translate("MainWindow", "快速查看"))
        self.semisup_tb.setText(_translate("MainWindow", "TB查看"))
        self.semisup_tb_close.setText(_translate("MainWindow", "关闭端口"))
        self.groupBox.setTitle(_translate("MainWindow", "监督学习"))
        self.choice_sup.setText(_translate("MainWindow", "选择exp"))
        self.sup_btn.setText(_translate("MainWindow", "快速查看"))
        self.sup_tb.setText(_translate("MainWindow", "TB查看"))
        self.sup_tb_close.setText(_translate("MainWindow", "关闭端口"))

